### ISSUE TITLE
Docker installation failed ubuntu 14.04

### ISSUE THREAD

**Issue by syntlyx** [blinkreaction/drude#144]
_~/Projects_ dsh install prerequisites
Installing prerequisites...
Installing Docker...
docker: unrecognized service
sudo: docker: command not found
dsh: Docker installation/upgrade has failed. 

https://dl.dropboxusercontent.com/u/77004167/Screenshots/screen_2016-07-04_18-57-12_window.png

**Comment by achekulaev** [comment]
Thanks @sy2nyk it is fixed in dsh 1.20.4 and will be released soon.

If you need resolution right now please install docker manually and then run prerequisites installation again to install docker-compose and other required configuration.

```
curl -sSL https://get.docker.com/ | sh && sudo usermod -aG docker $(whoami)
dsh install prerequisites
```

Feel free to comment here if you have any further issues with installing prerequisites.

**Comment by achekulaev** [comment]
@lmakarov https://github.com/blinkreaction/drude/commit/a647d0c34d1f90ccc7ba14bd722a301962a53c57

**Comment by syntlyx** [comment]
need add `sudo service docker start`
before `sudo docker version`

at 941 line

**Comment by achekulaev** [comment]
.

**Comment by achekulaev** [comment]
@sy2nyk Thanks. Indeed in case of update it is now required to start (it used to start automatically before). I've updated dsh. You can get developer version with `DRUDE_BRANCH=develop dsh update dsh`
