### ISSUE TITLE
[RESOLVED] Stale NFS handle error

### ISSUE THREAD

**Issue by haixiang** [blinkreaction/drude#20]
### Issue:

Virtual machine stops working within 15 - 25min  after fresh start. It keeps the "running" state in the virtualbox, but the sites it serves are failing to load.
### Symptoms:
- the machine's IP stops pinging.
- `ifconfig` inside the virtual machine shows that the main network adapter has changed the IP address (usually to 192.168.56.101) and the mask: 
  ![adapter](http://monosnap.com/image/C9koxgGh7SKjCgYfpwtVa27pTVrClU.png)
- trying to cd into the mounted directory inside the virtual machine throws "Stale NFS handle" error
### Resolution
1. Turn off the DHCP server for the adapter used by the virtual machine
   cmd+, 
   ![adapter_settings0](http://monosnap.com/image/ooRlFUHERHlddRxQL6hKTCiNVxEf1r.png)
   ![adapter_settings1](http://monosnap.com/image/rvGgQrPzLUGUbUJxmlbLOsuLwxrD0n.png)
   ![adapter_settings2](http://monosnap.com/image/gofswI4kPtvJKpoeDetGLktVrYzoOJ.png)
2. Destroy the virtual machine with `vagrant destroy`, delete all adapters in virtualbox, recreate the machine

**Comment by lmakarov** [comment]
@haixiang thanks for the report and solution! I only hope this was the original issue we all had with the Stale NFS handle error (https://github.com/blinkreaction/boot2docker-vagrant/issues/1) and that now we know what causes it and how it can be fixed :)

**Comment by lmakarov** [comment]
One note to the solution - you may not need to do a `vagrant destroy`.
Removing all host-only adapters it also a bit radical, but should not be hardfull and will clean up things.

So, if anyone runs into this issue again first try the following:
- remove all host-only adapters
- do `vagrant reload`
- check that the newly associated host-only adapter does NOT have the DHCP server enabled

**Comment by haixiang** [comment]
It appears that `vagrant destroy` is a required step. Simply rebuilding the images after turning off the DHCP does not resolve the issue.

**Comment by chipkaye** [comment]
Just planting a flag here that this step needs to be part of the install automation or added as an explicit manual step in the install docs.

**Comment by frankcarey** [comment]
WTF? Why doesn't the ip address change right away, why does it take ~20 minutes?This issue should be front and center on the installation docs in a troubleshooting section. For weeks we thought this was an NFS issue until I hunkered down to fix this for one of our developers and noticed the IP address in the VM was changing.  Here is some more helpful info at least...

Temporary fix (while the VM is running)

``` Bash
vagrant ssh #this may hang for a while (minute or two?) once you ssh in because it tries to cd you into the stale nfs folder which fails.
ifconfig eth1 192.168.10.10 netmask 255.255.255.0 #Update the ipaddress to what it's supposed to be.
```

Note that this may only last a few minutes before dhcp from vbox seems to recognize this and then reset your dhcp again. I tried to use `vagrant reload` after disabling the dhcp checkbox for vboxnet0 (double check the network the VM is using if you use VBox for other things)

To show where the settings are in OSX, go to Virtualbox > Preferences > Networks > Host Only Networks (tab) > vboxnet[N] > settings (screwdriver icon) > DHCP Server (tab) > Enable Server [Make sure this NOT enabled] 

### Other symptoms / data
- The nfs mount stops working because the ip address is changing
- containers stop responding (timeouts to browsers)
- looking at /var/log/udhcp.log you **should not** see 192.168.56.101 at the end. If you do it's going to break.. (you can see these lines right away, so you can save 20 minutes)
- this has nothing to do with the containers (it happens if you have a vm with containers loaded or not)
- simply disabling dhcp for vboxnet0, `vagrant destroy` and `vagrant up` **did not** fix the issue
- Issue **was fixed** though without doing a `vagrant destroy` by following https://github.com/blinkreaction/drude/issues/20#issuecomment-85639918 from @lmakarov ..(I needed to actually delete the host-only network adapter then restart the vm)

**Comment by lmakarov** [comment]
@frankcarey
https://github.com/blinkreaction/drude/blob/master/docs/troubleshooting.md
