### ISSUE TITLE
Cannot `show tables` with drush sqlc

### ISSUE THREAD

**Issue by mkorostoff** [blinkreaction/drude#5]
## Steps to reproduce:
1. SSH to your container
2. Drop into a mysql command prompt per issue #4 
3. Type `show tables;`
4. See that only a portion of the tables are shown.  Usually the output truncates around line 60, but occasionally truncates around line 40.  Occasionally all results shown.  Occasionally the first and last result shows, but several results in the middle are missing:

![showtables](https://cloud.githubusercontent.com/assets/1197335/6448988/a431ac72-c0eb-11e4-9b35-a5e97fa013d2.png)
## Expected Result:

That all tables would print out, and that I would be able to scroll back to the first result
![localmysql](https://cloud.githubusercontent.com/assets/1197335/6449061/2564bb90-c0ec-11e4-8036-fa1d9c411ac2.gif)

**Comment by lmakarov** [comment]
This is a bug in fig (docker-compose): https://github.com/docker/compose/issues/658
This comment suggest a workaround for now: https://github.com/docker/compose/issues/658#issuecomment-75124548

You basically have to enter the container with using `docker` command instead of `fig` like this

```
docker exec -it <full container name> bash
```

In your example this should look like: `docker exec -it drupal7_web_1 bash`

**Comment by mkorostoff** [comment]
Confirming that this worked for me!  Thanks!
