### ISSUE TITLE
Latest Solr changes cause 500 errors, should version changes.

### ISSUE THREAD

**Issue by frankcarey** [blinkreaction/drude#62]
4-5 days ago, our builds started to break. After a lot of debugging, we tracked it down to the Solr image changes of around the same time. I'm still not sure WHY those changes broke the builds (these are fresh builds from the testing server), but they did. We forked the repo to https://github.com/devinci-code/docker-drupal-solr and created our own docker builds to revert those changes and now everything works again. 

This is the second time that we've been nailed by breaking changes from blinkreaction repos, and without a clean way to go back to a working version besides forking it ourselves (drude and now the solr image). Can we please take advantage of tags (both in git and in docker) so projects depending on these images can stick to stable versions?

**Comment by lmakarov** [comment]
Hi @frankcarey, sorry for the broken build. We are aware of the problem and got some broken builds too...
Using tags would mean a lot of additional overhead (supporting release cycles for each of the images). Docker hub is also not very efficient with branches and tags and would rebuild ALL of the branches and tags in the repo every time there is a change to one of them.
I'm considering using docker image digests instead of tags in Drude's docker-compose.yml for truly immutable images. This would be like using a particular revision/build of an image.

**Comment by lmakarov** [comment]
@frankcarey I rolled back https://github.com/blinkreaction/docker-drupal-solr master branch and moved all recent refactoring to the develop branch.

Please switch to one of the following image tags:

```
blinkreaction/drupal-solr:3.x-stable (master)
blinkreaction/drupal-solr:4.x-stable (master)

blinkreaction/drupal-solr:3.x-latest (develop)
blinkreaction/drupal-solr:4.x-latest (develop)
```

The old tags will also work for now and point to master, but will be deprecated ones a stable build is produces after image refactoring.

**Comment by lmakarov** [comment]
Marking as resolved.
