### ISSUE TITLE
my.cnf and php.ini overrides not working

### ISSUE THREAD

**Issue by Nebel54** [blinkreaction/drude#63]
Hello and thanks for sharing drude! 

I've got a problem getting custom configurations for mysql running (using boot2docker an a mac). The docker-compse.yml contains those lines:

```
volumes:
 # MySQL configuration overrides
 - "./.drude/etc/mysql/my.cnf:/etc/mysql/conf.d/z_my.cnf"
```

Looking at the folder structure in ./.drude/etc/mysql/ the file my.cnf is a directory. If i put a file (e.g. my.cnf) into this folder, I end up with my config in the db container in /etc/mysql/conf.d/z_my.cnf/my.cnf.

I tried to change the mapping to "./.drude/etc/mysql:/etc/mysql/conf.d" which just results in an error:

```
Cannot start container 813d957396ceebbe7e954f60ab5508b2a860950915acb0d8f82474c33ef912e1: [8] System error: not a directory
```

Is this a common problem on mac os, or did I miss something? I use nfs as synced_folders method btw.

**Comment by Nebel54** [comment]
Replacing the folder ./.drude/etc/mysql/my.cnf also leads to the Error "System error: not a directory"

**Comment by Nebel54** [comment]
OK, it seems like this is a docker issue: https://github.com/docker/compose/issues/424. Mounting of single files should not work anymore.

**Comment by lmakarov** [comment]
Hi @Nebel54, grab examples from here https://github.com/blinkreaction/drude/tree/master/examples/.drude/etc and put them into `/.drude/etc` in your project. You can also check how things are wired in the [drude-testing](https://github.com/blinkreaction/drude-testing) project.

Restart containers with `dsh restart` (in the current stable release it will also restart the VM, this will change to restarting containers only in the next release). See if that works.

It is very possible that you will need to reset containers instead of just restarting, so that the old volume mounts are removed:
`dsh reset`

**Comment by lmakarov** [comment]
Mounting of a single file definitely works. We are using this setup and it works :)
Not sure what's the deal with https://github.com/docker/compose/issues/424
Try ^^ and report back.

**Comment by Nebel54** [comment]
Will do, thank you!

**Comment by Nebel54** [comment]
Thank you! Dropping the old vagrant image and setting everything up again did the trick. No idea what happened here…
