### ISSUE TITLE
Drupal 8 — drupal site:mode dev triggers a date.timezone setting warning

### ISSUE THREAD

**Issue by kyleskrinak** [blinkreaction/drude#74]
Running `dsh exec drupal site:mode dev` on a drude container will trigger a warning on every subsequent page load:

```
Warning: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in Drupal\Core\Datetime\DateFormatter->format() (line 110 of core/lib/Drupal/Core/Datetime/DateFormatter.php).
Warning: date_default_timezone_get(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in Drupal\Core\Cache\Context\TimeZoneCacheContext->getContext() (line 34 of core/lib/Drupal/Core/Cache/Context/TimeZoneCacheContext.php).
```

Running:  
`sed -ri 's/;date.timezone =/date.timezone = America\/New_York/g' /etc/php5/fpm/php.ini`

on the CLI volume addresses this issue — but is there a more automated way to handle this?

**Comment by lmakarov** [comment]
@kyleskrinak, sure. See docs here https://github.com/blinkreaction/drude/blob/develop/docs/settings.md
Make sure php.ini and my.cnf "files are not folders" on your local.
You may have to reset the containers (`dsh reset`) to get these picked up, since by default docker will create empty folders if a file mount does not exist. So when you replace the empty folders with the actual files, Docker may trip and will refuse to start containers.

**Comment by kyleskrinak** [comment]
Thanks, @lmakarov that works great on a new D8 instance. Perhaps I'm in error but, `dsh install drude` does not install the .drude folder on a new project. I must `dsh up` to create the .drude directory (as well as the soon-to-be-destroyed containers) add the php.ini files and then `dsh reset` for the php.ini to become incorporated. Is that correct?

Drude is fantastic, btw.

**Comment by lmakarov** [comment]
`dsh install drude` only grabs the `docker-compose.yml` file. The `.drude` directory is optional.
It does get created by Docker the first time you start containers with `dsh up`, since there is a mapping for the optional config files in `docker-compose.yml`.

So if you are setting up a brand new project and do need settings overrides (php.ini, my.cnf, etc.):
1. `dsh install drude`
2. (optional) copy the `.drude` folder from the examples [here](https://github.com/blinkreaction/drude/tree/develop/examples/.drude) and adjust as necessary
3. dsh up

If you skip step 2 above and get to it later on, then you will most likely need to `dsh reset`. Otherwise containers may not start because of the change with the mounts (dummy php.ini/etc folders becoming real files).

**Comment by kyleskrinak** [comment]
Excellent — thank you for your quick help.

**Comment by kyleskrinak** [comment]
FYI: You can run `svn export https://github.com/blinkreaction/drude/trunk/examples .drude` in your project directory to download the .drude files in one step
